/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface PnSideMenu {
    'open': () => Promise<void>;
    'opened': boolean;
    'text': string;
  }
  interface PnStockPrice {
    'stockSymbol': string;
  }
}

declare global {


  interface HTMLPnSideMenuElement extends Components.PnSideMenu, HTMLStencilElement {}
  var HTMLPnSideMenuElement: {
    prototype: HTMLPnSideMenuElement;
    new (): HTMLPnSideMenuElement;
  };

  interface HTMLPnStockPriceElement extends Components.PnStockPrice, HTMLStencilElement {}
  var HTMLPnStockPriceElement: {
    prototype: HTMLPnStockPriceElement;
    new (): HTMLPnStockPriceElement;
  };
  interface HTMLElementTagNameMap {
    'pn-side-menu': HTMLPnSideMenuElement;
    'pn-stock-price': HTMLPnStockPriceElement;
  }
}

declare namespace LocalJSX {
  interface PnSideMenu extends JSXBase.HTMLAttributes<HTMLPnSideMenuElement> {
    'opened'?: boolean;
    'text'?: string;
  }
  interface PnStockPrice extends JSXBase.HTMLAttributes<HTMLPnStockPriceElement> {
    'stockSymbol'?: string;
  }

  interface IntrinsicElements {
    'pn-side-menu': PnSideMenu;
    'pn-stock-price': PnStockPrice;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


